---
title: '01 Prep - `r unlist(strsplit(getwd(), "/"))[7]` - `r unlist(strsplit(getwd(), "/"))[8]`'
author:
  - name: "Emir Turkes [emir.turkes@eturkes.com]"
  - name: "UK Dementia Research Institute at UCL"
date: '`r strftime(Sys.time(), "%B %d, %Y")`'
bibliography: '../../../../`r unlist(strsplit(getwd(), "/"))[4]`.bib'
link-citations: true
output:
  html_document:
    code_folding: hide
    number_sections: true
    theme: lumen
    highlight: haddock
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(
    "..", "..", "..",
    "..", "results", unlist(strsplit(getwd(), "/"))[6],
    unlist(strsplit(getwd(), "/"))[7], unlist(strsplit(getwd(), "/"))[8], "01-prep.html"
  ))})
---

<style type="text/css">
body {font-size: 16px;}
h1.title {font-size: 35px;}
h1 {font-size: 24px;}
h2 {font-size: 22px;}
h3 {font-size: 20px;}
.toc-content {padding-left: 0px; padding-right: 0px;}
div.tocify {width: 100%;}
.tocify-subheader .tocify-item {font-size: 0.95em; padding-left: 25px; text-indent: 0;}
.tocify-subheader .tocify-subheader .tocify-item {
  font-size: 0.95em; padding-left: 35px; text-indent: 0;
}
div.main-container {max-width: none; width: 100%;}
</style>

*This file is a part of the [Pathology Signatures Project](https://github.com/eturkes/pathology-signatures).*

In this document we prepare the gene count matrix for downstream analysis.
The data here is derived from @`r unlist(strsplit(getwd(), "/"))[7]` and will be referenced using the name ``r unlist(strsplit(getwd(), "/"))[7]``.
This analysis focuses on NFT (tangle-bearing) neurons from the dataset.

# References

This is the concluding section of the document.
Here we output the `sessionInfo` and create a bibliography for works cited.

```{r}
sessionInfo()
```
